### ISSUE TITLE
[Design] 디자인 변경에 대하여

### ISSUE THREAD

**Issue by DongGeon0908** [o-ing/o-ing-frontend#2]
![image](https://user-images.githubusercontent.com/50691225/138206965-0c7eceb9-40b8-4370-8d05-aa88dfb18e56.png)
 현재 메인 헤더는 위의 사진과 같습니다! 개인적으로 해당 보라색보다 파스텔 톤이 조금 더 예쁠 것 같아요!!

#E2E1F3 또는 #C5C8E5 둘 중 하나가 어울릴 것 같다고 생각해요!

![image](https://user-images.githubusercontent.com/50691225/138207558-5c3cb834-993d-47ef-bf1f-687dbf5bd3c1.png)

동아리 생성하기 모달에서도 메인페이지의 박스처럼 둥글둥글하면 좋을 것 같습니다!

메인페이지에서는 저희 시스템이 뭔가 둥글둥글 포근포근 느낌인데, 갑자기 각진 스타일이 나오면 조금 당황스러운 느낌?이 드는 것 같아요!

**Comment by DongGeon0908** [comment]
이번 배포 내용을 보고, 엄청 고생하셨다는 것을 느끼게 되었네요 ㅜㅜ

한가지 바라는 점을 ISSUE로 남기겠습니당!!

![image](https://user-images.githubusercontent.com/50691225/138549966-857049c8-5e13-4afe-8583-fa1614bf2987.png)
현재 동아리 홈페이지가 해당 화면으로 제공하는게 조금 어색하게 느껴지는 것 같습니다 ㅜㅜ

컴포넌트 구조를 조금 변경하면 더 좋을 것 같아요! 어떻게 디자인을 잡을지는 같이 고민해요!

**Comment by jinn2u** [comment]
추후에 변경하도록 하겠습니다!
